### ISSUE TITLE
Add support for Chromium

### ISSUE THREAD

**Issue by JourneyOver** [Farow/userscripts#3]
pretty much what the issue name suggests, for some odd reason I can't get the new comment highlighting to work at all (even if there are new comments on the page since last visit) no matter what I do. it doesn't even bring up the "Highlight comments posted since previous visit [hh:mm] ago:" thing either.

**Comment by Farow** [comment]
Are you using Chrome?

**Comment by JourneyOver** [comment]
Yea, I'm using chrome. Still haven't gotten this to work for some reason yet.

**Comment by Farow** [comment]
Doesn't quite work on Chrome, related to [a bug](https://code.google.com/p/chromium/issues/detail?id=538558) which seems to have been fixed on Canary with the `chrome://flags/#enable-experimental-web-platform-features` flag enabled. Still needs a couple of tweaks to properly work, I'll see if I can add support for it.

**Comment by Farow** [comment]
Fixed by 2fc409e7faecba29fca3b96badc25db9f57e5c0c. Works on latest stable version (48) with `chrome://flags/#enable-experimental-web-platform-features` enabled.

**Comment by JourneyOver** [comment]
Still not working for me, I'm running the latest version of chrome and have the experimental web platform features turned on in the flags and I still can't get anything to show up. Guess I'll just have to continue sticking with JonnyRobbies script...

**Comment by Farow** [comment]
What version of Tampermonkey are you on? Does anything show up in the developer's console?
It's working fine for me:

![image](https://dl.dropboxusercontent.com/s/fq96hp1vam1ri23/screenshot%20408.png)

**Comment by JourneyOver** [comment]
Running the beta version of tampermonkey, but I tried the stable release as well and it ended up doing the same thing... Threw up a big syntax error and a few small ones as well.. 

link below to show what console errors are coming up.

https://paste.ee/r/zrRhy

errors are split up by "----" so it's easy to tell which errors start where.

**Comment by Farow** [comment]
Could you also try enabling `chrome://flags/#enable-javascript-harmony`?

**Comment by JourneyOver** [comment]
That worked, as soon as I enabled that and then relaunched chrome and went back on reddit no more errors or anything from the script.
